### ISSUE TITLE
R23 updates from 2020

### ISSUE THREAD

**Issue by matdon17** [nvs-vocabs/R23#1]
There was discussion about adding an ARVOR_L and possibly ARVOR_L with RBR CTDs rather than SeaBird.  ARVOR_L was added I believe, but I do not know where discussion about an RBR equipped version reached.  Key contacts were Mathieu Belboech (Ocean OPS) and Jerome Sagot (NKE).

**Comment by vpaba** [comment]
Note: there is an ongoing discussion re: ARVOR_L inclusion in Argo Reference Table 23 / R23 (see https://docs.google.com/spreadsheets/d/1Aw8B7FFUjG4e9MveD5qqvI7ZbB-z_x32IQnpHZbXVZA/edit#gid=2). We cannot create a new entry for it until a platform type key has been assigned to it.
