### ISSUE TITLE
Create Jumbo floats entries

### ISSUE THREAD

**Issue by vturpin** [nvs-vocabs/R23#3]
2 new type of floats are requested here :

- PROVOR_V - Jumbo
- PROVOR_III - Jumbo

One of them is already at sea.

Could you let me know what is needed to describe the platform type ?

**Comment by tcarval** [comment]
These two floats types are now valid in table 23.
The Jumbo floats are now available on GDAC.

Todo : Victor should create 2 new entries for WMO IXIXIX (1770)

**Comment by gwemon** [comment]
Should these not be added to [R23](https://vocab.nerc.ac.uk/collection/R23/current/)?

**Comment by tcarval** [comment]
> Should these not be added to [R23](https://vocab.nerc.ac.uk/collection/R23/current/)?

Yes indeed, I added it in the todo list

**Comment by cgourcuf** [comment]
"PROVOR_V - Jumbo" is listed in R23 but not "PROVOR_III - Jumbo".

**Comment by tcarval** [comment]
I just added "PROVOR_III - Jumbo" in R23.
It should be public on NVS within hours.
The format checker was correct with "PROVOR_III - Jumbo" in R23.

**Comment by tcarval** [comment]
I just added "PROVOR_III - Jumbo" in R23.
It should be public on NVS within hours.
The format checker was correct with "PROVOR_III - Jumbo" in R23.
